### ISSUE TITLE
Broken style to script conversion when there is comment before document block after global part

### ISSUE THREAD

**Issue by myfonj** [greasyfork-org/greasyfork#1245]
The global part seems to be completely omitted from JS version of userstyle when there is a comment before `@-moz-document` block at the end of the "global" part.

Test: https://greasyfork.org/en/scripts/486968-test-style-for-debugging-conversion-to-userscript/code?version=1325339

https://update.greasyfork.org/scripts/486968/1325339/Test%20style%20for%20debugging%20conversion%20to%20userscript.user.css :

```CSS
...

/**/
el { color: green; }

/**/
@-moz-document domain("facebook.com") { el { color: red; } }
```

produces https://update.greasyfork.org/scripts/486968/1325339/Test%20style%20for%20debugging%20conversion%20to%20userscript.user.js :

```JavaScript
...
// @include http://facebook.com/*
// @include https://facebook.com/*
// @include http://*.facebook.com/*
// @include https://*.facebook.com/*
// @downloadURL none
// ==/UserScript==

(function() {
let css = ` el { color: red; } `;
...
```

NB there is no `el { color: green; }` whatsoever.

While https://greasyfork.org/en/scripts/486968-test-style-for-debugging-conversion-to-userscript/code?version=1325324

https://update.greasyfork.org/scripts/486968/1325324/Test%20style%20for%20debugging%20conversion%20to%20userscript.user.css

```CSS
...

/**/
el { color: green; }

@-moz-document domain("facebook.com") { /**/ el { color: red; } }
```

produces 

```JavaScript
...
// @include *
// @downloadURL none
// ==/UserScript==

(function() {
let css = "";
css += `

/**/

el { color: green; }

`;
if ((location.hostname === "facebook.com" || location.hostname.endsWith(".facebook.com"))) {
  css += ` /**/ el { color: red; } `;
}
...
```

What is OK.

Got couple of bugreports for https://greasyfork.org/en/scripts/408378-unround-everything-everywhere/feedback when hit this problem.
